version: "3.1"
services:
  node-app:
    image: node:18
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]
    depends_on:
      - redis

  mongo:
    image: mongo:xenial
    container_name: mongo-container
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis/redis-stack-server:latest
    container_name: my-redis-container
    ports:
      - "6379:6379"

volumes:
  mongo_data:
    driver: local
